-- ============================================================================
-- SANTI · Libro de Reclamaciones virtual (INDECOPI · Ley N° 29571).
-- Correr en Supabase → SQL Editor → Run.
-- ============================================================================

create table if not exists public.reclamaciones (
  id                uuid primary key default gen_random_uuid(),
  numero            bigint generated by default as identity, -- correlativo de la hoja
  -- 1) Identificación del consumidor reclamante
  nombre            text not null,
  documento_tipo    text not null default 'DNI',   -- DNI | CE | Pasaporte
  documento_numero  text not null,
  domicilio         text,
  telefono          text,
  email             text not null,
  es_menor          boolean not null default false,
  apoderado         text,                            -- si es menor de edad
  -- 2) Identificación del bien contratado
  bien_tipo         text not null default 'servicio', -- producto | servicio
  bien_monto        numeric,
  bien_descripcion  text not null,
  -- 3) Detalle de la reclamación y pedido
  tipo              text not null default 'reclamo',  -- reclamo | queja
  detalle           text not null,
  pedido            text not null,
  -- Gestión interna
  estado            text not null default 'pendiente', -- pendiente | atendido
  respuesta         text,
  created_at        timestamptz default now()
);

create index if not exists reclamaciones_created_idx
  on public.reclamaciones (created_at desc);

alter table public.reclamaciones enable row level security;

-- Cualquiera puede registrar una reclamación (formulario público)
drop policy if exists "reclamaciones_insert" on public.reclamaciones;
create policy "reclamaciones_insert"
  on public.reclamaciones for insert
  to anon, authenticated
  with check (true);

-- Solo el administrador (autenticado) puede leerlas y gestionarlas
drop policy if exists "reclamaciones_admin_read" on public.reclamaciones;
create policy "reclamaciones_admin_read"
  on public.reclamaciones for select
  to authenticated using (true);

drop policy if exists "reclamaciones_admin_update" on public.reclamaciones;
create policy "reclamaciones_admin_update"
  on public.reclamaciones for update
  to authenticated using (true) with check (true);
