-- ============================================================================
-- SANTI · SETUP COMPLETO (idempotente). Correr TODO en Supabase → SQL Editor.
-- Incluye: contenido del sitio, galerías por sección, equipo, reclamaciones.
-- No borra datos existentes. Se puede correr varias veces sin problema.
-- ============================================================================

-- ── Contenido editable (videos y fotos sueltas) ────────────────────────────
create table if not exists public.site_content (
  key         text primary key,
  kind        text not null default 'video',
  url         text,
  updated_at  timestamptz default now()
);
alter table public.site_content enable row level security;
drop policy if exists "site_content_read" on public.site_content;
create policy "site_content_read" on public.site_content for select using (true);
drop policy if exists "site_content_write" on public.site_content;
create policy "site_content_write" on public.site_content for all to authenticated using (true) with check (true);

-- ── Galería / slider / testimonios / responsabilidad social ────────────────
create table if not exists public.site_gallery (
  id          uuid primary key default gen_random_uuid(),
  url         text not null,
  caption     text default '',
  sort        int  not null default 0,
  created_at  timestamptz default now()
);
-- 👇 LA COLUMNA QUE FALTABA:
alter table public.site_gallery
  add column if not exists section text not null default 'home';
create index if not exists site_gallery_sort_idx
  on public.site_gallery (section, sort, created_at);
alter table public.site_gallery enable row level security;
drop policy if exists "site_gallery_read" on public.site_gallery;
create policy "site_gallery_read" on public.site_gallery for select using (true);
drop policy if exists "site_gallery_write" on public.site_gallery;
create policy "site_gallery_write" on public.site_gallery for all to authenticated using (true) with check (true);

-- ── Equipo (Nuestros profesionales) ────────────────────────────────────────
create table if not exists public.site_team (
  id          uuid primary key default gen_random_uuid(),
  url         text not null,
  name        text default '',
  role        text default '',
  sort        int  not null default 0,
  created_at  timestamptz default now()
);
create index if not exists site_team_sort_idx on public.site_team (sort, created_at);
alter table public.site_team enable row level security;
drop policy if exists "site_team_read" on public.site_team;
create policy "site_team_read" on public.site_team for select using (true);
drop policy if exists "site_team_write" on public.site_team;
create policy "site_team_write" on public.site_team for all to authenticated using (true) with check (true);

-- ── Bucket de media del sitio ──────────────────────────────────────────────
insert into storage.buckets (id, name, public)
  values ('site-media', 'site-media', true) on conflict (id) do nothing;
drop policy if exists "site_media_read" on storage.objects;
create policy "site_media_read" on storage.objects for select using (bucket_id = 'site-media');
drop policy if exists "site_media_write" on storage.objects;
create policy "site_media_write" on storage.objects for all to authenticated
  using (bucket_id = 'site-media') with check (bucket_id = 'site-media');

-- ── Libro de Reclamaciones (INDECOPI · Ley N° 29571) ───────────────────────
create table if not exists public.reclamaciones (
  id                uuid primary key default gen_random_uuid(),
  numero            bigint generated by default as identity,
  nombre            text not null,
  documento_tipo    text not null default 'DNI',
  documento_numero  text not null,
  domicilio         text,
  telefono          text,
  email             text not null,
  es_menor          boolean not null default false,
  apoderado         text,
  bien_tipo         text not null default 'servicio',
  bien_monto        numeric,
  bien_descripcion  text not null,
  tipo              text not null default 'reclamo',
  detalle           text not null,
  pedido            text not null,
  estado            text not null default 'pendiente',
  respuesta         text,
  created_at        timestamptz default now()
);
alter table public.reclamaciones enable row level security;
drop policy if exists "reclamaciones_insert" on public.reclamaciones;
create policy "reclamaciones_insert" on public.reclamaciones for insert to anon, authenticated with check (true);
drop policy if exists "reclamaciones_admin_read" on public.reclamaciones;
create policy "reclamaciones_admin_read" on public.reclamaciones for select to authenticated using (true);
drop policy if exists "reclamaciones_admin_update" on public.reclamaciones;
create policy "reclamaciones_admin_update" on public.reclamaciones for update to authenticated using (true) with check (true);

-- ── Testimonios públicos (comentarios con estrellas, con moderación) ───────
create table if not exists public.testimonios_publicos (
  id         uuid primary key default gen_random_uuid(),
  segment    text not null,
  name       text not null,
  role       text,
  rating     int  not null,
  quote      text not null,
  approved   boolean not null default false,
  created_at timestamptz not null default now()
);
alter table public.testimonios_publicos add column if not exists approved boolean not null default false;
alter table public.testimonios_publicos enable row level security;
drop policy if exists "testimonios_read" on public.testimonios_publicos;
drop policy if exists "testimonios_read_public" on public.testimonios_publicos;
create policy "testimonios_read_public" on public.testimonios_publicos for select to anon using (approved = true);
drop policy if exists "testimonios_read_admin" on public.testimonios_publicos;
create policy "testimonios_read_admin" on public.testimonios_publicos for select to authenticated using (true);
drop policy if exists "testimonios_insert" on public.testimonios_publicos;
create policy "testimonios_insert" on public.testimonios_publicos for insert to anon, authenticated
  with check (char_length(name) between 1 and 60 and char_length(quote) between 3 and 500 and rating between 1 and 5);
drop policy if exists "testimonios_admin_update" on public.testimonios_publicos;
create policy "testimonios_admin_update" on public.testimonios_publicos for update to authenticated using (true) with check (true);
drop policy if exists "testimonios_admin_delete" on public.testimonios_publicos;
create policy "testimonios_admin_delete" on public.testimonios_publicos for delete to authenticated using (true);

-- ── Forzar recarga del esquema (para que PostgREST vea la columna nueva) ────
notify pgrst, 'reload schema';
